import = ["/Users/askoufis/.config/alacritty/linux.toml", "/Users/askoufis/.config/alacritty/mac.toml", "/Users/askoufis/.config/alacritty/colours.toml"]
live_config_reload = true

[env]
# Fix tmux + vim + alacritty colours
# https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6#alacritty
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = false
