[colors]
draw_bold_text_with_bright_colors = true

# vim moonfly from https://github.com/bluz71/vim-moonfly-colors/blob/c4ae6851441edfe74f7fb46b0e8cc43f534b0aa5/terminal_themes/alacritty.yml
[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c2c292"

[colors.cursor]
cursor = "#9e9e9e"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"
