#!/usr/bin/env fish

echo "Installing dotfiles"\n

# Ensure stow commands are always executed from within the repo
pushd ~/code/askoufis/dotfiles

for folder in (string split " " $STOW_FOLDERS)
    echo -n "Installing "
    set_color -o white
    echo $folder
    set_color normal
    stow -R -t ~/ $folder
end

echo \n"Installing open-in-nvim-launcher"\n

mkdir -p ~/.local/bin
cp open-in-nvim-launcher ~/.local/bin/open-in-nvim-launcher
chmod +x ~/.local/bin/open-in-nvim-launcher

echo \n"Building bat cache"\n

bat cache --build

popd

set_color -o white
echo \n"Done!"
set_color normal
