require('user.keymaps')
require('user.options')
require('user.plugins')
require('user.plugin-config.impatient')
require('user.colorscheme')
require('user.autocommands')
require('user.lsp')

require('user.plugin-config.telescope')
require('user.plugin-config.neotree')
require('user.plugin-config.mason')
require('user.plugin-config.tmux')
require('user.plugin-config.lualine')
require('user.plugin-config.treesitter')
require('user.plugin-config.luasnip')
require('user.plugin-config.cmp')
require('user.plugin-config.gitsigns')
require('user.plugin-config.cokeline')

require('globals')
