require('user.keymaps')
require('user.options')
require('user.impatient')
require('user.plugins')

require('user.mason')
require('user.tmux')
require('user.telescope')
require('user.surround')
require('user.lualine')
require('user.treesitter')
require('user.glow')
require('user.colorscheme')
require('user.cmp')
require('user.lsp')
require('user.comment')
require('user.gitsigns')
require('user.cokeline')
require('user.fidget')
require('user.indent-blankline')
require('user.neogit')
require('user.leap')
require('user.luasnip')

require('globals')
