require('user.keymaps')
require('user.options')
require('user.plugins')
require('user.colorscheme')
require('user.lsp')

require('user.plugin-config.impatient')
require('user.plugin-config.telescope')
require('user.plugin-config.neotree')
require('user.plugin-config.mason')
require('user.plugin-config.tmux')
require('user.plugin-config.autopairs')
require('user.plugin-config.surround')
require('user.plugin-config.lualine')
require('user.plugin-config.treesitter')
require('user.plugin-config.glow')
require('user.plugin-config.cmp')
require('user.plugin-config.comment')
require('user.plugin-config.gitsigns')
require('user.plugin-config.cokeline')
require('user.plugin-config.fidget')
require('user.plugin-config.indent-blankline')
require('user.plugin-config.neogit')
require('user.plugin-config.luasnip')

require('globals')
