[font]
size = 11.0

[font.bold]
family = "NotoSansM NF"
style = "Bold"

[font.bold_italic]
family = "NotoSansM NF"
style = "Bold Italic"

[font.italic]
family = "NotoSansM NF"
style = "Italic"

[font.normal]
family = "NotoSansM NF"
style = "Regular"
