"window.dynamic_title" = true
window_opacity = 1.0

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[hints.url]
modifiers = "None"

# Make Option + HJKL work like Alt + HJKL in neovim
# https://github.com/alacritty/alacritty/issues/93#issuecomment-271043197
[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

# For nvim autopairs fast wrap keybind
[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

# For nvim quickfix
[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

# Tmux plugin cleanup
[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

# tshjkl.nvim
[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

# Neovim github copilot keymaps
[[keyboard.bindings]]
chars = "\u001B["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B]"
key = "RBracket"
mods = "Alt"

  # Fix Ctrl + Space
[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[mouse]
hide_when_typing = false

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
dynamic_padding = false

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
